### ISSUE TITLE
Hackathon Introduction Page

### ISSUE THREAD

**Issue by junaidrahim** [hackathonistas/hackathonistas.github.io#5]
A page where a newbie could learn what a hackathon is and how to get started. 
Some content for the group is available at the README file of this repo: 
https://github.com/ayonroy2000/Hackathonistas_TelegramGroup

But a more visually attractive and detailed page answering questions like

* What is a Hackathon ?
* How are Hackathons conducted ?
* What is the point of it ?
* Opportunities ?
* How to get started ?
* Skills and Technologies Required
* How to form Teams ?
* Prizes, Important Websites
* Organizing Companies etc.

**Comment by ayonroy2000** [comment]
# What is a Hackathon ?

- A hackathon (also known as a hack day, hackfest or codefest) is a design sprint-like event in which computer programmers and others involved in software development, including graphic designers, interface designers, project managers, and others, often including domain experts, collaborate intensively on software projects. The goal of a hackathon is to create usable software or hardware with the goal of creating a functioning product by the end of the event.

# Who can attend a hackathon?

- ANYONE can attend . Yep, you read it right. Anyone who is interested in computer programming and loves to learn and build cool stuff can attend. If a hackathon targets a specific audience (ex, college students), then obviously only college students are allowed to attend but there are hackathons for everyone.

# Do I need to have programming experience? 

NO. You don’t. The organizers usually hold workshops throughout the hackathon for anyone who is new to programming or someone who wishes to learn more about a particular topic. Mentors are also available 24/7. So if you go to a hackathon without knowing what you want to do, that’s totally fine because you will have these mentors at your service to help and guide you.

# How much do I have to pay to attend a hackathon? 

- It’s FREE. Almost all hackathons are free of cost. Though some hackathons like AngelHack etc. do have a registration cost . Also, some hackathons provide travel reimbursements. :)

# Why should I attend a hackathon? 

- It’s a win- win situation for you. And here’s why:

    FREE FOOD.
    FREE SWAG. (Developers live for them. Ha,ha !!)
    Meet new people
    Meet recruiters
    Not expensive.
    Can help land an interview if you are looking for job opportunities.
    LEARN new things.

**Comment by junaidrahim** [comment]
We will need to add more content later. But its fine for now
